### ISSUE TITLE
double resume on ctrl-c

### ISSUE THREAD

**Issue by ioquatix** [socketry/async#41]
```
^CTraceback (most recent call last):
        9: from /home/samuel/.rvm/gems/ruby-head/gems/async-container-0.14.1/lib/async/container/forked.rb:64:in `block in spawn'
        8: from /home/samuel/.rvm/gems/ruby-head/gems/async-container-0.14.1/lib/async/container/group.rb:42:in `fork'
        7: from /home/samuel/.rvm/gems/ruby-head/gems/async-container-0.14.1/lib/async/container/group.rb:42:in `fork'
        6: from /home/samuel/.rvm/gems/ruby-head/gems/async-container-0.14.1/lib/async/container/forked.rb:67:in `block (2 levels) in spawn'
        5: from /home/samuel/.rvm/gems/ruby-head/gems/async-container-0.14.1/lib/async/container/controller.rb:47:in `block in async'
        4: from /home/samuel/.rvm/gems/ruby-head/gems/async-1.20.1/lib/async/reactor.rb:54:in `run'
        3: from /home/samuel/.rvm/gems/ruby-head/gems/async-1.20.1/lib/async/reactor.rb:171:in `run'
        2: from /home/samuel/.rvm/gems/ruby-head/gems/timers-4.3.0/lib/timers/group.rb:76:in `wait'
        1: from /home/samuel/.rvm/gems/ruby-head/gems/async-1.20.1/lib/async/reactor.rb:205:in `block in run'
/home/samuel/.rvm/gems/ruby-head/gems/async-1.20.1/lib/async/reactor.rb:205:in `select': Interrupt
        23: from /home/samuel/.rvm/gems/ruby-head/gems/async-container-0.14.1/lib/async/container/forked.rb:64:in `block in spawn'
        22: from /home/samuel/.rvm/gems/ruby-head/gems/async-container-0.14.1/lib/async/container/group.rb:42:in `fork'
        21: from /home/samuel/.rvm/gems/ruby-head/gems/async-container-0.14.1/lib/async/container/group.rb:42:in `fork'
        20: from /home/samuel/.rvm/gems/ruby-head/gems/async-container-0.14.1/lib/async/container/forked.rb:67:in `block (2 levels) in spawn'
        19: from /home/samuel/.rvm/gems/ruby-head/gems/async-container-0.14.1/lib/async/container/controller.rb:47:in `block in async'
        18: from /home/samuel/.rvm/gems/ruby-head/gems/async-1.20.1/lib/async/reactor.rb:56:in `run'
        17: from /home/samuel/.rvm/gems/ruby-head/gems/async-1.20.1/lib/async/reactor.rb:56:in `ensure in run'
        16: from /home/samuel/.rvm/gems/ruby-head/gems/async-1.20.1/lib/async/reactor.rb:223:in `close'
        15: from /home/samuel/.rvm/rubies/ruby-head/lib/ruby/2.7.0/set.rb:338:in `each'
        14: from /home/samuel/.rvm/rubies/ruby-head/lib/ruby/2.7.0/set.rb:338:in `each_key'
        13: from /home/samuel/.rvm/gems/ruby-head/gems/async-1.20.1/lib/async/task.rb:153:in `stop'
        12: from /home/samuel/.rvm/rubies/ruby-head/lib/ruby/2.7.0/set.rb:338:in `each'
        11: from /home/samuel/.rvm/rubies/ruby-head/lib/ruby/2.7.0/set.rb:338:in `each_key'
        10: from /home/samuel/.rvm/gems/ruby-head/gems/async-1.20.1/lib/async/task.rb:153:in `stop'
         9: from /home/samuel/.rvm/rubies/ruby-head/lib/ruby/2.7.0/set.rb:338:in `each'
         8: from /home/samuel/.rvm/rubies/ruby-head/lib/ruby/2.7.0/set.rb:338:in `each_key'
         7: from /home/samuel/.rvm/gems/ruby-head/gems/async-1.20.1/lib/async/task.rb:153:in `stop'
         6: from /home/samuel/.rvm/rubies/ruby-head/lib/ruby/2.7.0/set.rb:338:in `each'
         5: from /home/samuel/.rvm/rubies/ruby-head/lib/ruby/2.7.0/set.rb:338:in `each_key'
         4: from /home/samuel/.rvm/gems/ruby-head/gems/async-1.20.1/lib/async/task.rb:153:in `stop'
         3: from /home/samuel/.rvm/rubies/ruby-head/lib/ruby/2.7.0/set.rb:338:in `each'
         2: from /home/samuel/.rvm/rubies/ruby-head/lib/ruby/2.7.0/set.rb:338:in `each_key'
         1: from /home/samuel/.rvm/gems/ruby-head/gems/async-1.20.1/lib/async/task.rb:149:in `stop'
/home/samuel/.rvm/gems/ruby-head/gems/async-1.20.1/lib/async/task.rb:149:in `resume': double resume (FiberError)
```

**Comment by ioquatix** [comment]
This needs further investigation.

**Comment by ioquatix** [comment]
Let's see if we can make a reproduction.

**Comment by ioquatix** [comment]
@emiltin if you have a short repro or some way of reproducing, that would be super helpful.

**Comment by ioquatix** [comment]
Here is the current implementation for `stop`:

```
		# Stop the task and all of its children.
		# @return [void]
		def stop
			if self.stopping?
				# If we are already stopping this task... don't try to stop it again.
				return true
			elsif self.running?
				@status = :stopping
				
				if self.current?
					raise Stop, "Stopping current fiber!"
				elsif @fiber&.alive?
					@fiber.resume(Stop.new)
				end
			end
		ensure
			@children&.each(&:stop) # line 153
		end
```

**Comment by ioquatix** [comment]
I'd like to figure out a repro before just assuming that we can fix the problem, because it would be good to add a spec.

The solution might be to remove the `ensure` block and move it into the `elsif` block, so that we avoid doing it a 2nd time. I'm not sure if this can cause issues. In theory, invoking stop could create more subtasks (e.g. in client `ensure` blocks), but this is unlikely. Maybe we can signal this as an error (i.e. can't create more tasks when stopping).

**Comment by ioquatix** [comment]
I've added a potential fix - we move `@children.each(&:stop)` into `stop!` state transition, and we more clearly define how that can get invoked. State transitions should only get executed once, so it at least fixes that being called multiple times. But I don't think it fixes the root cause.

**Comment by ioquatix** [comment]
Can you try the branch and see if you can repro the issue? or if you run into any other issues?

**Comment by emiltin** [comment]
I can try the branch, but will not have time before early next week. Then I can also try to create a reproduction. The error is consistent, but there's quite a bit of code involved, so need to shave it down.

**Comment by ioquatix** [comment]
That would be awesome.

Is there any code I can try out on my own time too?

**Comment by emiltin** [comment]
Sorry, the code is not in a public repo yet, although I expect that it will be at a later time.

**Comment by ioquatix** [comment]
Please make a short repro, this is an important bug to fix. But we can't do it without a repro.

**Comment by emiltin** [comment]
Hi @ioquatix, sent you an invite for a repo with a reproduction. I removed as much code as I could, but it's not so easy to get it down to something really small. To run: ruby ./repro.rb

**Comment by emiltin** [comment]
I still get a double resume error with the stop-fix branch.

**Comment by ioquatix** [comment]
Okay, the repro was helpful, I'm investigating.

**Comment by ioquatix** [comment]
Okay, here is a repro of your specific case:

```ruby
#!/usr/bin/env ruby

require 'async'
require 'async/queue'

Async do
	condition = Async::Condition.new
	
	producer = Async do |subtask|
		(1..).each do |value|
			condition.signal(value)
			subtask.sleep(1)
		end
	end
	
	while value = condition.wait
		if value
			producer.stop
		end
	end
end
```

This might seem confusing, but the correct way to fix this is to change `Async::Condition` to `Async::Notification`. I made a PR to the code you shared me.

The reason for this is because there is a difference in the way control flow works.

With `Async::Condition`, when the condition is triggered, you directly transfer to the finer that is waiting.

With `Async::Notification`, you yield back to the reactor, and next iteration of the event loop will resume your code.

The difference is the hierarchy of resume.

With Condition:

- Reactor -> Your Task (condition.signal) -> Other Task (condition.wait)

With Notification

- Reactor -> Your Task (condition.signal) -> enqueue into Reactor
- Reactor -> Other Task (condition.wait)

In the case of `Condition`:

- Reactor -> Your Task (condition.signal) -> Other Task (condition.wait)

If the other task tries to resume your task directly, it ends up with double resume. Notification avoids this because the resume is not tested, but comes from the reactor.

Now, the question, why are these different and where is it used?

`Async::Condition` is simpler, has less overhead, and directly resumes the other code. This works like a parent-child relationship and only makes sense when you explicitly know this relationship exists:

```ruby
Async do |producer|
	condition = Async::Condition.new
	
	consumer = Async do
		while value = condition.wait
			$stderr.puts "consuming #{value}"
		end
	end
	
	(1..5).each do |value|
		$stderr.puts "generating #{value}"
		condition.signal(value)
		producer.sleep(0.1)
	end
ensure
	consumer.stop
end

puts "done"
```

This is totally fine because the consumer calling `condition.wait` is nested in the parent task.

If you just have completely arbitrary relationships between tasks waiting, using `Async::Notification` will avoid any issues, at the expense of slightly more overhead since it will round-trip through the reactor, but this ensures you have a flat nesting.

**Comment by emiltin** [comment]
Thank you for investigating!

It's easy to understand that a Condition transfer directly to another fiber, while Notification first goes back to the reactor, and then to the waiting task.

But I don't understanding when and why a Condition will result in a double resume error.

Naively, it would be nice if stopping a task would never result in an error. If using the condition works fine, then why should it be a problem to stop doing so?

**Comment by ioquatix** [comment]
Because:

- Resume parent task
- Wait on condition
- Resume child task
- `condition.signal` -> parent.resume
-> stop
-> parent.resume(stop) (double resume)

I agree, stop should work in all cases. I'll need to think about it.

**Comment by ioquatix** [comment]
Here are two options I thought of:

- When calling stop, the task and all children are queued up into the reactor to be stopped on the next iteration. Well, the flow control is completely changed and also if the parent creates more children in the mean time, it would not be stopped.
- When calling stop on a child that was already resumed (and has not yielded, so can't be resumed), we instead mark it as stopped. When the parent task is stopped, when yielding for the last time, we yield the Async::Stop exception. However, there is no code for dealing with this, and there are places where `fiber.resume` is called directly - we'd need to add something like `task.resume` which could do this behaviour.

The first case _may_ be simpler, and the issue of creating more children could be solved by throwing an exception when trying to create a child task for a parent that is stopping.

That being said, it changes flow control significantly - it might even cause deadlock.

Here is a minimal repro I tidied up from the initial one given above:

```ruby
#!/usr/bin/env ruby

require 'async'
require 'async/queue'

Async do |consumer|
	condition = Async::Condition.new
	
	producer = Async do |subtask|
		(1..).each do |value|
			subtask.yield # (1) Fiber.yield, (3) Reactor -> producer.resume
			condition.signal(value) # (4) consumer.resume(value)
		end
	end
	
	while value = condition.wait # (2) value = Fiber.yield
		producer.stop # (5) [producer is resumed already] producer.stop
	end
end
```

I'm not really concerned about the code, but what is the right semantic model - i.e. how should this work? What should `producer.stop` do?

One final point to bear in mind, while `#stop` should work as much as possible, there must be some situations where it can fail, e.g. if you have an ensure block that does something odd and breaks the `#stop` process.

**Comment by ioquatix** [comment]
@emiltin do you mind reviewing the PR #47 and tell me what you think?

If we can't stop the fiber now, we schedule it into the reactor to be stopped later.

**Comment by emiltin** [comment]
Hi,
Your reproduction still results in a double resume error for me, is that intended? I'm using this branch/commit via bundler:
Using async 1.20.1 from https://github.com/socketry/async (at stop-fix@c7153df)

I not familiar with the internals of async, so it's hard for me to comment on the proposed fix. But I would think consumer.stop should simply cause the task (and sub tasks) not be scheduled (resumed) anymore. Why does stopping a task have to resume it?

My understanding is that a double resume error happens when resume is called on a fiber that's already running, or resume is called on a fiber that transferred to another fiber. Somehow the double resume is related the fact that Async::Condition uses Fiber#transfer, but I don't exactly get why.

A short repro:

```ruby
require 'async'

Async do |consumer|
	condition = Async::Condition.new
	producer = Async do |subtask|
		subtask.yield 			# (1) Fiber.yield, (3) Reactor -> producer.resume
		condition.signal(1) # (4) consumer.resume(value)
	end
	condition.wait 				# (2) value = Fiber.yield
	producer.stop 				# (5) [producer is resumed already] producer.stop
end
```

**Comment by ioquatix** [comment]
The repro you give should be fixed on this branch.

**Comment by ioquatix** [comment]
Make sure you use 97075ddfb4440d339757da967b6f3c00394218a6

**Comment by emiltin** [comment]
The error still seems to persist, even on commit 97075dd:

```
Emils-iMac:rsmp emiltin$ gem info async

*** LOCAL GEMS ***

async (1.20.1)
    Author: Samuel Williams
    Homepage: https://github.com/socketry/async
    License: MIT
    Installed at: /Users/emiltin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0

    Async is an asynchronous I/O framework based on nio4r.
Emils-iMac:rsmp emiltin$ bundle update async
Fetching https://github.com/socketry/async
Fetching gem metadata from https://rubygems.org/...
Resolving dependencies...
Using console 1.4.0
Using nio4r 2.4.0
Using timers 4.3.0
Using async 1.20.1 from https://github.com/socketry/async (at stop-fix@97075dd)
Using async-io 1.24.0
Using bundler 2.0.2
Bundler attempted to update async but its version stayed the same
Bundle updated!


Emils-iMac:rsmp emiltin$ cat repro.rb 
require 'async'

Async do |consumer|
	condition = Async::Condition.new
	producer = Async do |subtask|
		subtask.yield 			# (1) Fiber.yield, (3) Reactor -> producer.resume
		condition.signal(1) # (4) consumer.resume(value)
	end
	condition.wait 				# (2) value = Fiber.yield
	producer.stop 				# (5) [producer is resumed already] producer.stop
end


Emils-iMac:rsmp emiltin$ ruby ./repro.rb 
 0.01s    error: <Async::Task:0x3fcbc581fd64 failed> [pid=92308] [2019-08-21 12:32:34 +0200]
               |   FiberError: double resume
               |   → /Users/emiltin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/async-1.20.1/lib/async/task.rb:149 in `resume'
               |     /Users/emiltin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/async-1.20.1/lib/async/task.rb:149 in `stop'
               |     ./repro.rb:10 in `block in <main>'
               |     /Users/emiltin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/async-1.20.1/lib/async/task.rb:228 in `block in make_fiber'
Emils-iMac:rsmp emiltin$ ruby -b
Traceback (most recent call last):
ruby: invalid option -b  (-h will show valid options) (RuntimeError)


Emils-iMac:rsmp emiltin$ ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
```

For my own repo, I switched to Async::Notification everywhere for now, which get rids of the double resume error. The slight overhead is not a problem for me currently.

**Comment by ioquatix** [comment]
I don't think it's using the right gem:

```
               |   → /Users/emiltin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/async-1.20.1/lib/async/task.rb:149 in `resume'
```

Maybe try bundle exec?

**Comment by emiltin** [comment]
You're right.
```
bundle exec ruby ./repro.rb   # => no errors
```

**Comment by ioquatix** [comment]
Great, well, maybe this fix is good enough. I need to spend some more time thinking about it. But it's probably the only way to do it given all the different concerns.

**Comment by emiltin** [comment]
Super. Sorry I cannot provide more input on the commits at this point. 
Ddi you have any quick explanation on why stopping a task would resume it?

**Comment by ioquatix** [comment]
One of the guarantees that Async tries to provide, short of your computer literally busting into flames, is that `Async` blocks always run to completion, whatever that may be.

e.g.

```ruby
Async do
	file = File.open(...)
ensure
	file&.close
end
```

When you call stop, it raises an exception within the context of the fiber (resuming it and raising the exception). So, stopping a task causes it to be resumed, but an exception causes it to terminate as quickly as possible. Does that answer your question?

**Comment by emiltin** [comment]
I see. So it would be bad to simply remove the task from the scheduler?

**Comment by ioquatix** [comment]
Yes. Stop means graceful but immediate shutdown.

**Comment by ioquatix** [comment]
Okay, so I think we've almost got a fix for this. I'll try pushing it tomorrow.

**Comment by ioquatix** [comment]
This is fixed in v1.21.1 and is done by marking the task to be stopped on the next iteration through the run-loop.
